from Vehicle import Vehicle
from Ship import Ship
from Airplane import Airplane

# Input dummy data kelas Vehicle

print("==== VEHICLE DUMMY DATA TEST ===")
print("")

vehicle1 = Vehicle()
vehicle1.setName("BMW")
vehicle1.setFuelType("Pertalite")
vehicle1.setMaxPassengers(3)
vehicle1.setTerrain("Road")
vehicle1.setSpeed(300)
vehicle1.printVehicle()

print("")
vehicle2 = Vehicle()
vehicle2.setName("Aerox")
vehicle2.setFuelType("Dexlite")
vehicle2.setMaxPassengers(2)
vehicle2.setTerrain("Rugged")
vehicle2.setSpeed(120)
vehicle2.printVehicle()

print("")
vehicle3 = Vehicle()
vehicle3.setName("SuperJet")
vehicle3.setFuelType("Aftur")
vehicle3.setMaxPassengers(1)
vehicle3.setTerrain("Air")
vehicle3.setSpeed(1000)
vehicle3.printVehicle()

print("")
vehicle4 = Vehicle()
vehicle4.setName("Double Bike")
vehicle4.setFuelType("Water")
vehicle4.setMaxPassengers(2)
vehicle4.setTerrain("Road")
vehicle4.setSpeed(30)
vehicle4.printVehicle()

print("")
vehicle5 = Vehicle()
vehicle5.setName("Bugatti")
vehicle5.setFuelType("Shell")
vehicle5.setMaxPassengers(4)
vehicle5.setTerrain("Speedway")
vehicle5.setSpeed(450)
vehicle5.printVehicle()

print("")
print("====== SHIP DUMMY DATA TEST =====")
print("")

# Input dummy data kelas Ship
ship1 = Ship()
ship1.setName("Bounty")
ship1.setFuelType("Super Solar")
ship1.setMaxPassengers(550)
ship1.setTerrain("Water")
ship1.setSpeed(135)
ship1.setAge(12)
ship1.setShipType("Ferry")
ship1.setCountryOfManufacturer("Germany")
ship1.printShip()

print("")
ship2 = Ship()
ship2.setName("Lenin")
ship2.setFuelType("Solar Fuel")
ship2.setMaxPassengers(5000)
ship2.setTerrain("Water")
ship2.setSpeed(150)
ship2.setAge(31)
ship2.setShipType("Cargo")
ship2.setCountryOfManufacturer("Brazil")
ship2.printShip()

print("")
ship3 = Ship()
ship3.setName("Titanic")
ship3.setFuelType("Solar Iced")
ship3.setMaxPassengers(600)
ship3.setTerrain("Water")
ship3.setSpeed(250)
ship3.setAge(11)
ship3.setShipType("Ship Crusher")
ship3.setCountryOfManufacturer("New Zealand")
ship3.printShip()

print("")
ship4 = Ship()
ship4.setName("Santa Maria")
ship4.setFuelType("Solar")
ship4.setMaxPassengers(300)
ship4.setTerrain("Water")
ship4.setSpeed(120)
ship4.setAge(26)
ship4.setShipType("Passenger Ship")
ship4.setCountryOfManufacturer("USA")
ship4.printShip()

print("")
ship5 = Ship()
ship5.setName("Olympic")
ship5.setFuelType("Fosil Gas")
ship5.setMaxPassengers(3000)
ship5.setTerrain("Water")
ship5.setSpeed(100)
ship5.setAge(22)
ship5.setShipType("Ferry")
ship5.setCountryOfManufacturer("United Kingdom")
ship5.printShip()

print("")
print("====== AIRPLANE DUMMY DATA TEST =====")
print("")

# Input dummy data kelas Airplane
airplane1 = Airplane()
airplane1.setName("Atonov")
airplane1.setFuelType("Avtur")
airplane1.setMaxPassengers(2000)
airplane1.setTerrain("Air")
airplane1.setSpeed(670)
airplane1.setAge(22)
airplane1.setAirplaneType("Cargo plane")
airplane1.setWingsLength(71.8)
airplane1.printAirplane()

print("")
airplane2 = Airplane()
airplane2.setName("Hawker Hurricane")
airplane2.setFuelType("Premium Avtur")
airplane2.setMaxPassengers(3)
airplane2.setTerrain("Air")
airplane2.setSpeed(1100)
airplane2.setAge(32)
airplane2.setAirplaneType("Spy plane")
airplane2.setWingsLength(29.6)
airplane2.printAirplane()

print("")
airplane3 = Airplane()
airplane3.setName("MiG-21")
airplane3.setFuelType("Avtur")
airplane3.setMaxPassengers(5)
airplane3.setTerrain("Air")
airplane3.setSpeed(1000)
airplane3.setAge(43)
airplane3.setAirplaneType("Aircraft")
airplane3.setWingsLength(31)
airplane3.printAirplane()

print("")
airplane4 = Airplane()
airplane4.setName("Guppy plane")
airplane4.setFuelType("Avtur")
airplane4.setMaxPassengers(1000)
airplane4.setTerrain("Air")
airplane4.setSpeed(1000)
airplane4.setAge(20)
airplane4.setAirplaneType("Passenger")
airplane4.setWingsLength(47.63)
airplane4.printAirplane()

print("")
airplane5 = Airplane()
airplane5.setName("Cessna 172")
airplane5.setFuelType("Aviation")
airplane5.setMaxPassengers(2)
airplane5.setTerrain("Air")
airplane5.setSpeed(250)
airplane5.setAge(11)
airplane5.setAirplaneType("Single Engine")
airplane5.setWingsLength(11)
airplane5.printAirplane()

print("")
print("====== END OF FILE ======")